- name: load mongodb schema
  when: schema_setup == "mongo"
  block:

  - name: Copy Mongodb repo file
    ansible.builtin.template:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: Install mongodb client
    ansible.builtin.dnf:
      name: mongodb-org
      state: latest

  - name: Load Master data
    ansible.builtin.shell: mongosh --host mongo.{{ env }}.naifah.online </app/db/{{ item }}.js
    loop: "{{schema_files}}"

  - name: Load Mysql data
    when: schema_setup == "mysql"
    block:


  -  name: Install mysql schema
     ansible.builtin.dnf:
      name: mysql
     state: latest


- name: Load Master data
  ansible.builtin.shell: mysql -h mysql.{{ env }}.naifah.online -uroot -pRoboShop@1 < /app/db/{{ item }}.sql
  loop: "{{schema_files}}"