- name: Copy Mongodb repo file
  ansible.builtin.copy:
    src: mongod.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: Install mongodb client
  ansible.builtin.dnf:
    name: mongodb-monogsh
    state: latest

- name: Load Master data
  ansible.uiltin.shell: mongosh --host mongo.dev.naifah.online </app/db/master-data.js

